dependencies:
  provider: ^5.0.0 #Tambahkan ini

fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Regular.ttf
      - asset: assets/fonts/Lato-Bold.ttf
        weight: 700
  - family: Anton
    fonts:
      - asset: assets/fonts/Anton-Regular.ttf
  